export const MOCK_USERS = [
  { _id: "u1", name: "Aryan Mehta",    email: "aryan.mehta@gmail.com",    points: 15420, coins: 320, role: "user" },
  { _id: "u2", name: "Priya Sharma",   email: "priya.sharma@gmail.com",   points: 12100, coins: 210, role: "user" },
  { _id: "u3", name: "Rohan Das",      email: "rohan.das@gmail.com",      points: 11850, coins: 190, role: "user" },
  { _id: "u4", name: "Sneha Iyer",     email: "sneha.iyer@gmail.com",     points: 10400, coins: 160, role: "user" },
  { _id: "u5", name: "Karan Verma",    email: "karan.verma@gmail.com",    points: 9800,  coins: 140, role: "user" },
  { _id: "u6", name: "Nisha Pillai",   email: "nisha.pillai@gmail.com",   points: 8750,  coins: 120, role: "user" },
  { _id: "u7", name: "Dev Anand",      email: "dev.anand@gmail.com",      points: 8100,  coins: 100, role: "user" },
  { _id: "u8", name: "Anika Bose",     email: "anika.bose@gmail.com",     points: 7650,  coins: 90,  role: "user" },
];

export const MOCK_EXPERIENCES = [
  {
    _id: "e1",
    author: MOCK_USERS[0],
    company: "Google",
    role: "Software Engineer II",
    oaPlatform: "HackerRank",
    difficulty: "Hard",
    salaryLPA: 45,
    topics: ["Algorithms & DS", "Distributed Systems", "Googliness"],
    questionPatterns: ["Graph Traversal", "Dynamic Programming", "Sliding Window"],
    experienceText: `The Google SWE II loop consisted of 5 rounds over two days. The first round was a warm-up — two medium LeetCode problems on arrays and hashmaps, completed in 45 minutes on HackerRank. The interviewer was friendly and gave hints when I was stuck.\n\nRound 2 was the hardest — a graph problem involving finding the shortest path in a weighted directed graph with constraints. I used Dijkstra's but the follow-up required me to handle negative edges, so I switched to Bellman-Ford. The key insight was that the graph had at most 500 nodes so O(VE) was acceptable.\n\nSystem design round involved designing a URL shortener at Google scale — 10B URLs, 100K QPS reads, 1K QPS writes. I covered consistent hashing, Cassandra for storage, Redis for caching, and a Zookeeper-based counter for generating short IDs. The interviewer pushed hard on how I'd handle hot keys.\n\nGoogliness round was a behavioral deep-dive. They asked about a time I disagreed with a tech lead and how I handled it. Be specific — vague answers don't land here.\n\nOverall the process took 3 weeks from OA to offer. Compensation was ₹42L base + ₹8L stocks/year + ₹5L signing.`,
    upvotes: ["u2", "u3", "u4", "u5"],
    upvoteCount: 4,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e2",
    author: MOCK_USERS[1],
    company: "Stripe",
    role: "Backend Engineer",
    oaPlatform: "CodeSignal",
    difficulty: "Medium",
    salaryLPA: 38,
    topics: ["Distributed Systems", "Low-latency", "System Design"],
    questionPatterns: ["Sliding Window", "Trie", "Graph Traversal"],
    experienceText: `Stripe's interview process is among the most craft-focused I've experienced. The OA on CodeSignal had 4 questions — all standard but timed aggressively at 70 minutes total. The difficulty ranged from easy to hard. I solved 3 fully and got partial credit on the 4th.\n\nThe phone screen was a live coding session on a shared editor. The problem involved implementing a rate limiter — first with a simple counter, then with a sliding window log, then with a sliding window counter. Each step was a follow-up of the previous. This is classic Stripe — they want to see how you iterate.\n\nOn-site had 4 rounds: one more coding (implement a simplified version of Stripe's webhook retry system), one system design (design the payment processing pipeline for a high-volume merchant), one bug hunt (a real internal Stripe code snippet with 3 bugs to find), and one values interview.\n\nThe bug hunt round is unique to Stripe — pay attention to off-by-one errors in retry logic and race conditions in concurrent writes. These are the types of bugs they care about.\n\nOffer came in 2 weeks. Base was ₹36L with ₹8L annual equity refresh.`,
    upvotes: ["u1", "u3", "u5"],
    upvoteCount: 3,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e3",
    author: MOCK_USERS[2],
    company: "Meta",
    role: "Production Engineer",
    oaPlatform: "HackerRank",
    difficulty: "Hard",
    salaryLPA: 40,
    topics: ["Algorithms & DS", "Low-level Design", "Concurrency"],
    questionPatterns: ["Graph Traversal", "Backtracking", "Dynamic Programming"],
    experienceText: `Meta PE interviews are different from standard SWE loops. They test your ability to think about systems at the infrastructure level — not just write clean product code.\n\nThe OA had 2 coding problems and one debugging problem. The coding problems were graph-heavy — one on finding strongly connected components, one on minimum spanning trees. The debugging problem was a C++ snippet with a memory leak and a deadlock. Spot the issues, explain them, fix them.\n\nOn-site: coding round had a classic DP problem (edit distance) but the follow-up was to implement it with O(n) space instead of O(n²). Then a production engineering round where they give you a high CPU alert on a hypothetical server — walk through exactly how you'd debug it, what commands you'd run, what you'd look for.\n\nSystem design was designing Meta's notification delivery system — fan-out on write vs read, handling celebrity accounts with 50M followers, push vs pull for mobile clients.\n\nThe meta (pun intended) advice: for PE roles, know Linux internals cold. /proc filesystem, strace, perf, eBPF basics. They will ask.`,
    upvotes: ["u1", "u2", "u4", "u6", "u7"],
    upvoteCount: 5,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e4",
    author: MOCK_USERS[3],
    company: "Amazon",
    role: "SDE II",
    oaPlatform: "HackerRank",
    difficulty: "Medium",
    salaryLPA: 32,
    topics: ["Leadership Principles", "System Design", "Algorithms & DS"],
    questionPatterns: ["Sliding Window", "Dynamic Programming"],
    experienceText: `Amazon's process is dominated by Leadership Principles — do not underestimate the behavioral component. Even the technical rounds have LP questions woven in.\n\nOA: 2 coding problems, 1 work simulation, 1 LP questionnaire. The coding problems were medium difficulty — one on binary search, one on graphs. The work simulation is a series of email scenarios where you pick responses. There are no trick answers but they're testing judgment.\n\nPhone screen: one coding + one LP deep dive. The LP question was "Tell me about a time you disagreed with your manager." They will drill into every detail — what exactly did you say, what was the outcome, what would you do differently. STAR format is mandatory.\n\nOn-site: 4 rounds, each with 1-2 coding problems and 2 LP questions. The LP questions repeat across rounds because different interviewers are evaluating different principles. Prepare 6-8 strong stories and map them to all 16 LPs.\n\nSDE II base at Amazon Bangalore was ₹28L + ₹10L RSUs over 4 years (backloaded — 5%, 15%, 40%, 40%). Signing bonus of ₹3L.`,
    upvotes: ["u2", "u5", "u8"],
    upvoteCount: 3,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e5",
    author: MOCK_USERS[4],
    company: "Microsoft",
    role: "SWE",
    oaPlatform: "Codility",
    difficulty: "Medium",
    salaryLPA: 28,
    topics: ["Algorithms & DS", "System Design", "Behavioral"],
    questionPatterns: ["Dynamic Programming", "Trees", "Sliding Window"],
    experienceText: `Microsoft's process felt the most human of all FAANG interviews I've done. Interviewers are collaborative, not adversarial.\n\nOA on Codility: 3 problems in 90 minutes. Easy-medium-hard distribution. The hard problem was a tree DP that I didn't solve fully but still moved forward, which tells you they're not purely pass/fail on OA score.\n\nPhone screen: one coding (medium trees problem — LCA variant) + "why Microsoft" question. Be genuine here, they can tell when you're reading from a script.\n\nOn-site (4 rounds): round 1 was coding — implement a simple version of Excel cell dependency resolution (topological sort). Round 2 was system design — design OneDrive's file sync system across devices. Round 3 was coding again — a DP problem on word break. Round 4 was the "as appropriate" round with a senior manager, mostly behavioral.\n\nHiring manager reach-out came within 3 days. Total comp at Hyderabad was ₹26L base + ₹6L RSUs/year. Work-life balance is genuinely better than other FAANGs from what I've heard from people inside.`,
    upvotes: ["u1", "u3", "u6"],
    upvoteCount: 3,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e6",
    author: MOCK_USERS[5],
    company: "Razorpay",
    role: "Senior Software Engineer",
    oaPlatform: "HackerEarth",
    difficulty: "Medium",
    salaryLPA: 24,
    topics: ["System Design", "Low-level Design", "Algorithms & DS"],
    questionPatterns: ["Graph Traversal", "Sliding Window"],
    experienceText: `Razorpay's interviews are deeply practical — they want engineers who understand payment systems and can translate that to code.\n\nOA on HackerEarth: 3 problems, 90 minutes. Standard DSA. Nothing exotic.\n\nRound 1 (Low-level Design): Design a payment gateway SDK. Define classes, interfaces, relationships. They care about extensibility — what if you need to add a new payment method? What if you need to handle webhook retries? Think in terms of open-closed principle.\n\nRound 2 (Coding): Two problems — one on hashmaps, one dynamic programming. Medium difficulty. They gave hints freely which made it feel more like pair programming.\n\nRound 3 (System Design): Design Razorpay's settlement system — how do you reconcile merchant balances against bank statements at scale, handle partial failures, and ensure exactly-once processing. This was the hardest round. Know idempotency keys cold.\n\nRound 4 (Hiring Manager): Culture fit + growth discussion. Very conversational.\n\nTotal offer: ₹22L base + ₹3L variable + ESOPs worth roughly ₹4L at current valuation.`,
    upvotes: ["u2", "u4", "u7", "u8"],
    upvoteCount: 4,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e7",
    author: MOCK_USERS[6],
    company: "Uber",
    role: "Software Engineer",
    oaPlatform: "HackerRank",
    difficulty: "Hard",
    salaryLPA: 35,
    topics: ["Distributed Systems", "Algorithms & DS", "Concurrency"],
    questionPatterns: ["Graph Traversal", "Dynamic Programming", "Backtracking"],
    experienceText: `Uber's interview is famously heavy on systems thinking. Even the coding rounds have a systems flavor.\n\nOA: 2 coding problems. One was a graph problem — shortest path with time-varying edge weights (simulate Uber's dynamic routing). The second was a simulation problem — model a ride dispatch queue with priorities.\n\nPhone screen: one coding (medium graphs) + one discussion on a past project. They dug deep into an API design decision I made at a previous company — why did I choose REST over gRPC, what were the tradeoffs. Prepare to defend every architectural decision on your resume.\n\nOn-site: 5 rounds. Two coding, one system design, one distributed systems deep dive, one behavioral. The distributed systems round is separate from system design — here they give you a specific scenario (e.g. Uber Eats order goes through 6 microservices, one fails midway) and ask how you'd design the recovery.\n\nSystem design: design Uber's real-time driver location tracking system at 50M concurrent drivers. Geohashing, WebSockets vs SSE, Kafka for location event streaming, read replicas for the map service.\n\nBase offer: ₹32L + ₹12L RSUs over 4 years.`,
    upvotes: ["u1", "u2", "u3", "u5"],
    upvoteCount: 4,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e8",
    author: MOCK_USERS[7],
    company: "Flipkart",
    role: "SDE I",
    oaPlatform: "HackerRank",
    difficulty: "Easy",
    salaryLPA: 18,
    topics: ["Algorithms & DS", "Behavioral", "Low-level Design"],
    questionPatterns: ["Sliding Window", "Trees", "Dynamic Programming"],
    experienceText: `Flipkart's SDE I process is well-structured and campus-friendly. The difficulty is lower than FAANG but the speed expected is high.\n\nOA: 3 problems in 90 minutes. Easy-medium-medium. I solved all three. One was a string manipulation problem, one was a binary tree traversal, one was a simple DP (coin change variant).\n\nRound 1: Live coding — two problems. One easy (reverse a linked list), one medium (find all permutations of a string). They care about clean code — variable names, edge cases, test cases.\n\nRound 2: Low-level design — design a parking lot. Standard LLD question but they wanted full working code, not just class diagrams. Implement the ticketing system, billing, spot allocation.\n\nRound 3: Hiring manager — past projects, what you learned, how you debug. Very relaxed. They're checking communication and attitude more than technical depth here.\n\nOffer: ₹16L base + ₹2.5L variable. Good for freshers. Joining bonus of ₹1L. Walmart-owned so benefits are solid.`,
    upvotes: ["u3", "u4", "u6"],
    upvoteCount: 3,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e9",
    author: MOCK_USERS[0],
    company: "Netflix",
    role: "Senior Engineer",
    oaPlatform: "Karat",
    difficulty: "Hard",
    salaryLPA: 52,
    topics: ["System Design", "Distributed Systems", "Behavioral"],
    questionPatterns: ["Dynamic Programming", "Graph Traversal"],
    experienceText: `Netflix does not have a traditional OA. All interviews are live — they use Karat for the initial technical screen which is a third-party interview service with trained interviewers.\n\nKarat screen: 2 coding problems in 60 minutes. One medium arrays problem, one medium trees. The Karat interviewer was professional and gave structured hints. Passed to Netflix team.\n\nNetflix on-site is famous for being "freedom and responsibility" culture-focused. Every round starts with "tell me about a time you had to make a high-stakes technical decision with incomplete information." They want senior engineers who are comfortable with ambiguity.\n\nTechnical rounds: system design (design Netflix's video encoding pipeline — why VP9 over H.264, how do you generate 20 different quality levels per video, CDN strategy for global delivery), and a coding round focused on stream processing (process a stream of viewing events and return top-K shows in real time — min heap solution).\n\nNo "trick" leetcode questions. They care far more about system thinking and communication. You should be able to talk for 45 minutes about your previous system design decisions.\n\nComp: ₹48L base (all cash, no equity by default — Netflix pays top-of-market in cash). Truly exceptional package.`,
    upvotes: ["u2", "u4", "u5", "u6", "u7", "u8"],
    upvoteCount: 6,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e10",
    author: MOCK_USERS[1],
    company: "Apple",
    role: "Software Engineer",
    oaPlatform: "Codility",
    difficulty: "Medium",
    salaryLPA: 42,
    topics: ["Algorithms & DS", "Low-level Design", "Concurrency"],
    questionPatterns: ["Trees", "Dynamic Programming", "Sliding Window"],
    experienceText: `Apple's interview is secretive by design. NDAs are stricter than any other company I interviewed at — interviewers won't tell you what team you're interviewing for until very late in the process.\n\nOA on Codility: 3 problems, fairly standard. Medium difficulty. They specifically test runtime and memory complexity — brute force solutions that technically pass will fail here because of strict time limits.\n\nPhone screen: one coding (tree diameter problem) + discussion of a past project's architecture. Apple interviewers are laser-focused on your specific role's domain — if you're interviewing for Maps, they'll ask about geospatial indexing.\n\nOn-site (called "loop" internally): 5 rounds. The coding rounds heavily feature problems related to the team's actual work. I got questions about image processing pipelines (Metal framework concepts) and memory management in Objective-C/Swift ARC.\n\nThe culture round is the most important — Apple's culture is "the details matter." Bring examples of times you cared obsessively about craft, polish, or correctness.\n\nOffer: ₹38L base + ₹15L RSUs over 4 years + excellent hardware benefits.`,
    upvotes: ["u1", "u3", "u5", "u7"],
    upvoteCount: 4,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e11",
    author: MOCK_USERS[2],
    company: "Atlassian",
    role: "Software Engineer",
    oaPlatform: "HackerRank",
    difficulty: "Medium",
    salaryLPA: 30,
    topics: ["System Design", "Behavioral", "Algorithms & DS"],
    questionPatterns: ["Graph Traversal", "Sliding Window"],
    experienceText: `Atlassian's interview culture is the most laid-back of any tech company I've encountered. They explicitly tell you the interview is not adversarial — it's a "working session."\n\nOA: 2 coding problems. Standard medium difficulty. Passed easily.\n\nValues interview (happens early, not at the end like most companies): 30 minutes, purely behavioral. Atlassian values are "Open company, no bullshit" — they want people who give direct feedback and handle it graciously. Bring examples of times you gave hard feedback to a peer.\n\nTechnical rounds: one coding (implement a simplified Jira ticket dependency resolver — topological sort), one system design (design Confluence's real-time collaborative editing — CRDTs vs OT, conflict resolution).\n\nThe collaborative editing question is genuinely hard if you haven't seen CRDTs before. They don't expect a perfect answer — they want to see how you reason about consistency tradeoffs.\n\nFlex working hours and remote-first culture are real, not marketing. Multiple people on my panel were in different time zones. Offer: ₹28L base + ₹6L equity/year.`,
    upvotes: ["u4", "u5", "u8"],
    upvoteCount: 3,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "e12",
    author: MOCK_USERS[3],
    company: "Spotify",
    role: "Backend Engineer",
    oaPlatform: "HackerRank",
    difficulty: "Medium",
    salaryLPA: 36,
    topics: ["System Design", "Distributed Systems", "Algorithms & DS"],
    questionPatterns: ["Graph Traversal", "Dynamic Programming"],
    experienceText: `Spotify interviews lean heavily on their "Squad" model — they want to know how you work in autonomous, cross-functional teams.\n\nOA: 2 problems on HackerRank. One on arrays, one on graphs. Standard medium difficulty. 75 minutes.\n\nPhone screen: one coding (implement a playlist shuffle algorithm — Fisher-Yates, then discuss why naive modulo is biased) + culture conversation. The shuffle question is a classic Spotify question — know it cold.\n\nOn-site: system design (design Spotify's recommendation engine — collaborative filtering, content-based filtering, how to handle cold start for new users), coding (stream processing — find top-K songs across a stream of play events using a heap), and a squad simulation round where you discuss how you'd handle a technical disagreement with a designer and a PM.\n\nThe squad round is unique — they're evaluating whether you can communicate technical constraints to non-engineers without being condescending. Practice explaining tradeoffs in plain English.\n\nBase: ₹32L + ₹8L equity/year. Stockholm HQ roles pay 2-3x but require relocation.`,
    upvotes: ["u1", "u2", "u6", "u7"],
    upvoteCount: 4,
    isUpvotedByMe: false,
    isBookmarked: false,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_LEADERBOARD = MOCK_USERS.map((u) => ({
  ...u,
  dominantCategory: ["DSA", "System Design", "DSA", "HR", "System Design", "DSA", "System Design", "HR"][
    MOCK_USERS.indexOf(u)
  ],
}));

export const MOCK_TRENDING = [
  {
    _id: "t1",
    company: "Google",
    category: "AI & SEARCH",
    tags: ["HYDERABAD", "HARD", "₹45L+"],
    description: "The Googliness round is seeing a major shift — interviewers are increasingly probing for examples of ML system ownership, not just culture fit. Candidates report questions on model deployment pipelines appearing in behavioral rounds.",
    relatedExperience: "e1",
  },
  {
    _id: "t2",
    company: "Stripe",
    category: "GLOBAL PAYMENTS",
    tags: ["REMOTE", "ELITE", "₹38L"],
    description: "Stripe's bug hunt round is the most-discussed topic this week. The pattern: a realistic payments codebase with subtle race conditions and retry logic errors. Community members have been sharing preparation strategies.",
    relatedExperience: "e2",
  },
  {
    _id: "t3",
    company: "Netflix",
    category: "STREAMING INFRA",
    tags: ["BANGALORE", "HARD", "₹52L+"],
    description: "Netflix's Karat screen pass rate has reportedly dropped. Candidates who passed 6 months ago are now failing the same style of questions. The community suspects stricter scoring rubrics after a hiring freeze period.",
    relatedExperience: "e9",
  },
  {
    _id: "t4",
    company: "Uber",
    category: "MAPS & DISPATCH",
    tags: ["BANGALORE", "HARD", "₹35L"],
    description: "Uber's distributed systems deep-dive round is generating the most discussion this month. The failure recovery scenario pattern has appeared in 7 out of 9 recent reports.",
    relatedExperience: "e7",
  },
  {
    _id: "t5",
    company: "Razorpay",
    category: "FINTECH",
    tags: ["BANGALORE", "MEDIUM", "₹24L"],
    description: "Razorpay's LLD round format has shifted from whiteboarding to live coding. Candidates must now implement the full class hierarchy in a shared editor, not just diagram it.",
    relatedExperience: "e6",
  },
];

export const MOCK_COMPARE_DATA = {
  Amazon: {
    passRate: "12%", difficultyScore: "4.2", avgTC: "₹38,00,000",
    location: "Bangalore", category: "E-Commerce & Cloud",
    tcNote: "+₹4L vs market average",
    interviewFocus: ["Leadership Principles", "System Design", "Algorithms & DS"],
    funnel: [88, 62, 28, 12],
    salaryGrowth: [32, 38, 55, 82],
  },
  Google: {
    passRate: "0.8%", difficultyScore: "4.9", avgTC: "₹45,00,000",
    location: "Hyderabad", category: "Search & AI",
    tcNote: "+₹14L vs market average",
    interviewFocus: ["Algorithms & DS", "Distributed Systems", "Googliness"],
    funnel: [92, 48, 18, 0.8],
    salaryGrowth: [38, 45, 68, 95],
  },
  Meta: {
    passRate: "2%", difficultyScore: "4.7", avgTC: "₹42,00,000",
    location: "Bangalore", category: "Social & AI",
    tcNote: "+₹11L vs market average",
    interviewFocus: ["Algorithms & DS", "System Design", "Concurrency"],
    funnel: [90, 52, 22, 2],
    salaryGrowth: [36, 42, 64, 88],
  },
  Apple: {
    passRate: "3%", difficultyScore: "4.5", avgTC: "₹42,00,000",
    location: "Hyderabad", category: "Consumer Hardware & OS",
    tcNote: "+₹10L vs market average",
    interviewFocus: ["Low-level Design", "Concurrency", "Algorithms & DS"],
    funnel: [85, 55, 25, 3],
    salaryGrowth: [34, 42, 60, 82],
  },
  Netflix: {
    passRate: "1.5%", difficultyScore: "4.8", avgTC: "₹52,00,000",
    location: "Bangalore", category: "Streaming Infra",
    tcNote: "+₹22L vs market average",
    interviewFocus: ["System Design", "Distributed Systems", "Behavioral"],
    funnel: [94, 58, 12, 1.5],
    salaryGrowth: [45, 52, 75, 110],
  },
  Microsoft: {
    passRate: "8%", difficultyScore: "3.9", avgTC: "₹28,00,000",
    location: "Hyderabad", category: "Cloud & Productivity",
    tcNote: "+₹2L vs market average",
    interviewFocus: ["Algorithms & DS", "System Design", "Behavioral"],
    funnel: [82, 65, 35, 8],
    salaryGrowth: [24, 28, 42, 65],
  },
  Stripe: {
    passRate: "4%", difficultyScore: "4.6", avgTC: "₹38,00,000",
    location: "Remote", category: "Payments Infrastructure",
    tcNote: "+₹9L vs market average",
    interviewFocus: ["System Design", "Low-latency", "Distributed Systems"],
    funnel: [80, 42, 18, 4],
    salaryGrowth: [35, 38, 58, 85],
  },
  Uber: {
    passRate: "5%", difficultyScore: "4.4", avgTC: "₹35,00,000",
    location: "Bangalore", category: "Maps & Dispatch",
    tcNote: "+₹7L vs market average",
    interviewFocus: ["Distributed Systems", "Algorithms & DS", "Concurrency"],
    funnel: [85, 52, 22, 5],
    salaryGrowth: [30, 35, 52, 78],
  },
  Twitter: {
    passRate: "6%", difficultyScore: "4.1", avgTC: "₹30,00,000",
    location: "Remote", category: "Social Media",
    tcNote: "+₹3L vs market average",
    interviewFocus: ["System Design", "Algorithms & DS", "Behavioral"],
    funnel: [80, 58, 28, 6],
    salaryGrowth: [28, 30, 48, 70],
  },
  Salesforce: {
    passRate: "10%", difficultyScore: "3.7", avgTC: "₹26,00,000",
    location: "Hyderabad", category: "CRM & Cloud",
    tcNote: "At market average",
    interviewFocus: ["System Design", "Behavioral", "Algorithms & DS"],
    funnel: [82, 60, 32, 10],
    salaryGrowth: [22, 26, 38, 55],
  },
  NVIDIA: {
    passRate: "2.5%", difficultyScore: "4.8", avgTC: "₹55,00,000",
    location: "Pune", category: "GPU & AI Infrastructure",
    tcNote: "+₹24L vs market average",
    interviewFocus: ["Algorithms & DS", "Concurrency", "Low-level Design"],
    funnel: [90, 45, 15, 2.5],
    salaryGrowth: [48, 55, 82, 120],
  },
  Tesla: {
    passRate: "7%", difficultyScore: "4.3", avgTC: "₹32,00,000",
    location: "Bangalore", category: "Automotive & AI",
    tcNote: "+₹5L vs market average",
    interviewFocus: ["System Design", "Concurrency", "Algorithms & DS"],
    funnel: [84, 54, 24, 7],
    salaryGrowth: [28, 32, 50, 75],
  },
};
